language: ruby
sudo: true
rvm:
- 2.5.0
services:
- docker
script:
- echo "Done"
deploy:
  provider: script
  script: bin/build-image
  on:
    branch: master
notifications:
  slack:
    secure: ZjR6tYtU43ljb8gRz94BHKlVKlN/GHHVV/gviF7tQ3nokeNXDV7lLSr4wzHTXuLtO2Ta3kxM4L0eRS7nnTWiDVag1JJ/mxo5DJzu0D5e1eJtJ6O+NLOtrydWI/OPe45fArOai6YuwOoNVGUFF2bM1E72Eedx19nLbmq+ASqebrDWnoRslAqAjkydEQeot6LBNlFdUe3xLe6sBKBazLIq/QkmyII74kMXH+sUUMqgV88bvH57QEwuabN1UZSnkEfLNOuHJkh/HYc+6GzydNxNKZ4fOgPOVWxA07t+wd3ISStGRKK9bs9vKhJuBtoo/H8RXiQvzQA4tRodIFAmHd3e+BPDBbFVJxP5AlL35h4NMPZI56h2fE5zYR5i1MD7wk5z4/b5KB+WgVDJMN63L5Dqq14C/JYB4Zj0NPXqsTlErqCSEwZGuVuplyoTynqf8KYkrqZzTTcot696NslKJgRBBdIYu28JVdrtYGEYXaxDjM2CAAV9/g/O03CT5JjIhOWP+R5rxu35QDOEiJAuDz0TjLSOGhm353K+Czn0RiEK/8KgG2BfLqxFUMPV+kvHx76peKqRoT1U4PaYCDa4zjxtJKIstgMYKMV4HzeT1SKHvzNrUkdvRu5oCRR4z8yVcPBOFr71RNmNxRadDVDGHHFlCxFhmq+zHErdPYDYIWfYt2E=
